name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setze Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Ändern Sie diese Zeile auf '3.8'
    - name: Installiere Abhängigkeiten
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Baue Paket
      run: python -m build
    - name: Veröffentliche Paket
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
