name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        echo "[distutils]" >> ~/.pypirc
        echo "index-servers = pypi" >> ~/.pypirc
        echo "[pypi]" >> ~/.pypirc
        echo "username = $TWINE_USERNAME" >> ~/.pypirc
        echo "password = $TWINE_PASSWORD" >> ~/.pypirc
        echo "token = $TWINE_TOKEN" >> ~/.pypirc
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

    - name: Cleanup
      run: |
        rm -rf dist
        rm -rf build
