name: Publish Package

on:
  push:
    tags:
      - 'v*' # Veröffentlichen Sie das Paket nur für Tags, die mit 'v' beginnen (z.B. v1.0, v2.0)

jobs:
  publish:
    runs-on: ubuntu-latest # Verwenden Sie einen Ubuntu-Laufzeitumgebung
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Verwenden Sie Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish to GitHub Packages
      run: twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

    - name: Cleanup
      run: |
        rm -rf dist
        rm -rf build
